-- MySQL Script generated by MySQL Workbench
-- Fri Jul 28 08:36:05 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema juridico
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `juridico` ;

-- -----------------------------------------------------
-- Schema juridico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `juridico` DEFAULT CHARACTER SET utf8 ;
USE `juridico` ;

-- -----------------------------------------------------
-- Table `juridico`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `juridico`.`Usuarios` (
  `usuarios_id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_nome` VARCHAR(20) NOT NULL,
  `usuarios_senha` VARCHAR(32) NOT NULL,
  `usuarios_grupo` INT NOT NULL,
  `usuarios_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`usuarios_id`),
  UNIQUE INDEX `usuarios_nome_UNIQUE` (`usuarios_nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`Pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`Pessoas` ;

CREATE TABLE IF NOT EXISTS `juridico`.`Pessoas` (
  `pessoas_id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NULL,
  `pessoas_cpf` VARCHAR(16) NOT NULL,
  `pessoas_rg` VARCHAR(16) NOT NULL,
  `pessoas_nome` VARCHAR(50) NOT NULL,
  `pessoas_datanasc` DATE NOT NULL,
  `pessoas_email` VARCHAR(50) NOT NULL,
  `pessoas_tel` VARCHAR(20) NOT NULL,
  `pessoas_sexo` CHAR(1) NOT NULL,
  `pessoas_oab` VARCHAR(45) NOT NULL,
  `pessoas_endereco` VARCHAR(50) NOT NULL,
  `pessoas_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`pessoas_id`),
  UNIQUE INDEX `pessoas_cpf_UNIQUE` (`pessoas_cpf` ASC),
  UNIQUE INDEX `pessoas_email_UNIQUE` (`pessoas_email` ASC),
  UNIQUE INDEX `pessoas_tel_UNIQUE` (`pessoas_tel` ASC),
  UNIQUE INDEX `pessoas_rg_UNIQUE` (`pessoas_rg` ASC),
  INDEX `fkpessoas_usuarios_id_idx` (`usuarios_id` ASC),
  CONSTRAINT `fkpessoas_usuarios_id`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `juridico`.`Usuarios` (`usuarios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`Varas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`Varas` ;

CREATE TABLE IF NOT EXISTS `juridico`.`Varas` (
  `varas_id` INT NOT NULL,
  `varas_nome` VARCHAR(50) NOT NULL,
  `varas_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`varas_id`),
  UNIQUE INDEX `varas_nome_UNIQUE` (`varas_nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`Processos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`Processos` ;

CREATE TABLE IF NOT EXISTS `juridico`.`Processos` (
  `processos_id` INT NOT NULL AUTO_INCREMENT,
  `processos_num` VARCHAR(50) NOT NULL,
  `processos_acao` VARCHAR(100) NOT NULL,
  `processos_ordem` VARCHAR(45) NULL,
  `varas_id` INT NOT NULL,
  `processos_oficial` VARCHAR(50) NOT NULL,
  `processos_juiz` VARCHAR(50) NOT NULL,
  `processos_apencos` VARCHAR(50) NOT NULL,
  `processos_valor` DECIMAL NULL,
  `processos_senha` CHAR(10) NOT NULL,
  `processos_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`processos_id`),
  UNIQUE INDEX `processos_num_UNIQUE` (`processos_num` ASC),
  UNIQUE INDEX `processos_ordem_UNIQUE` (`processos_ordem` ASC),
  INDEX `fkprocessos_varas_nome_idx` (`varas_id` ASC),
  CONSTRAINT `fkprocessos_varas_nome`
    FOREIGN KEY (`varas_id`)
    REFERENCES `juridico`.`Varas` (`varas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`Partes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`Partes` ;

CREATE TABLE IF NOT EXISTS `juridico`.`Partes` (
  `partes_id` INT NOT NULL AUTO_INCREMENT,
  `pessoas_id` INT NOT NULL,
  `processos_id` INT NOT NULL,
  `tipo` CHAR(10) NOT NULL,
  `partes_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`partes_id`),
  UNIQUE INDEX `partes_numproc_UNIQUE` (`processos_id` ASC),
  INDEX `fkpessoas_id_idx` (`pessoas_id` ASC),
  CONSTRAINT `fkpartes_pessoas_id`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `juridico`.`Pessoas` (`pessoas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkpartes_processos_id`
    FOREIGN KEY (`processos_id`)
    REFERENCES `juridico`.`Processos` (`processos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`Assuntos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`Assuntos` ;

CREATE TABLE IF NOT EXISTS `juridico`.`Assuntos` (
  `assuntos_id` INT NOT NULL AUTO_INCREMENT,
  `processos_id` INT NOT NULL,
  `assustos_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`assuntos_id`),
  INDEX `fkprocessos_id_idx` (`processos_id` ASC),
  CONSTRAINT `fkassuntos_processos_id`
    FOREIGN KEY (`processos_id`)
    REFERENCES `juridico`.`Processos` (`processos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`Indices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`Indices` ;

CREATE TABLE IF NOT EXISTS `juridico`.`Indices` (
  `indices_id` INT NOT NULL AUTO_INCREMENT,
  `assuntos_id` INT NOT NULL,
  `indice_desc` VARCHAR(100) NOT NULL,
  `indice_del` CHAR(1) NULL,
  UNIQUE INDEX `indice_desc_UNIQUE` (`indice_desc` ASC),
  PRIMARY KEY (`indices_id`),
  INDEX `fkassuntos_id_idx` (`assuntos_id` ASC),
  CONSTRAINT `fkindices_assuntos_id`
    FOREIGN KEY (`assuntos_id`)
    REFERENCES `juridico`.`Assuntos` (`assuntos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`Andamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`Andamentos` ;

CREATE TABLE IF NOT EXISTS `juridico`.`Andamentos` (
  `andamentos_id` INT NOT NULL AUTO_INCREMENT,
  `processos_id` INT NOT NULL,
  `andamentos_tipo` VARCHAR(45) NOT NULL,
  `andamentos_com` LONGBLOB NOT NULL,
  `andamentos_data` DATE NOT NULL,
  `andamentos_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`andamentos_id`),
  INDEX `fkandamentos_processos_id_idx` (`processos_id` ASC),
  CONSTRAINT `fkandamentos_processos_id`
    FOREIGN KEY (`processos_id`)
    REFERENCES `juridico`.`Processos` (`processos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`Arquivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`Arquivos` ;

CREATE TABLE IF NOT EXISTS `juridico`.`Arquivos` (
  `arquivos_id` INT NOT NULL AUTO_INCREMENT,
  `andamentos_id` INT NOT NULL,
  `arquivos_arq` LONGBLOB NULL,
  `arquivos_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`arquivos_id`),
  INDEX `fkandamentos_id_idx` (`andamentos_id` ASC),
  CONSTRAINT `fkarquivos_andamentos_id`
    FOREIGN KEY (`andamentos_id`)
    REFERENCES `juridico`.`Andamentos` (`andamentos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`Logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`Logs` ;

CREATE TABLE IF NOT EXISTS `juridico`.`Logs` (
  `logs_id` INT NOT NULL,
  `logs_data` TIMESTAMP(0) NULL,
  `logs_usuario` VARCHAR(45) NULL,
  `logs_tipo` VARCHAR(45) NULL,
  `logs_del` CHAR(1) NULL,
  PRIMARY KEY (`logs_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `juridico`.`Usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `juridico`;
INSERT INTO `juridico`.`Usuarios` (`usuarios_id`, `usuarios_nome`, `usuarios_senha`, `usuarios_grupo`, `usuarios_del`) VALUES (default, 'andrei', 'e10adc3949ba59abbe56e057f20f883e', 1, 'n');

COMMIT;

