-- MySQL Script generated by MySQL Workbench
-- Wed Oct 25 12:05:00 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema juridico
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `juridico` ;

-- -----------------------------------------------------
-- Schema juridico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `juridico` DEFAULT CHARACTER SET utf8 ;
USE `juridico` ;

-- -----------------------------------------------------
-- Table `juridico`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `juridico`.`usuarios` (
  `usuarios_id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_nome` VARCHAR(20) NOT NULL,
  `usuarios_senha` VARCHAR(32) NOT NULL,
  `usuarios_grupo` INT NOT NULL,
  `usuarios_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`usuarios_id`),
  UNIQUE INDEX `usuarios_nome_UNIQUE` (`usuarios_nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`pessoas` ;

CREATE TABLE IF NOT EXISTS `juridico`.`pessoas` (
  `pessoas_id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NULL,
  `pessoas_cpf_cnpj` VARCHAR(16) NOT NULL,
  `pessoas_rg` VARCHAR(16) NULL,
  `pessoas_nome` VARCHAR(50) NOT NULL,
  `pessoas_datanasc` DATE NOT NULL,
  `pessoas_email` VARCHAR(50) NULL,
  `pessoas_tel` VARCHAR(20) NULL,
  `pessoas_sexo` CHAR(1) NOT NULL,
  `pessoas_oab` VARCHAR(45) NULL,
  `pessoas_endereco` VARCHAR(50) NULL,
  `pessoas_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`pessoas_id`),
  UNIQUE INDEX `pessoas_cpf_UNIQUE` (`pessoas_cpf_cnpj` ASC),
  UNIQUE INDEX `pessoas_rg_UNIQUE` (`pessoas_rg` ASC),
  INDEX `fkpessoas_usuarios_id_idx` (`usuarios_id` ASC),
  UNIQUE INDEX `pessoas_email_UNIQUE` (`pessoas_email` ASC),
  CONSTRAINT `fkpessoas_usuarios_id`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `juridico`.`usuarios` (`usuarios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`varas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`varas` ;

CREATE TABLE IF NOT EXISTS `juridico`.`varas` (
  `varas_id` INT NOT NULL AUTO_INCREMENT,
  `varas_nome` VARCHAR(50) NOT NULL,
  `varas_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`varas_id`),
  UNIQUE INDEX `varas_nome_UNIQUE` (`varas_nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`processos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`processos` ;

CREATE TABLE IF NOT EXISTS `juridico`.`processos` (
  `processos_id` INT NOT NULL AUTO_INCREMENT,
  `processos_num` VARCHAR(50) NOT NULL,
  `processos_acao` VARCHAR(100) NOT NULL,
  `processos_ordem` VARCHAR(45) NULL,
  `varas_id` INT NOT NULL,
  `processos_oficial` VARCHAR(50) NOT NULL,
  `processos_juiz` VARCHAR(50) NOT NULL,
  `processos_apensos` INT NULL,
  `processos_valor` DECIMAL(7,2) NULL,
  `processos_senha` CHAR(10) NULL,
  `processos_data` DATE NOT NULL,
  `processos_procurador` VARCHAR(50) NULL,
  `processos_desembargador` VARCHAR(50) NULL,
  `processos_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`processos_id`),
  UNIQUE INDEX `processos_num_UNIQUE` (`processos_num` ASC),
  INDEX `fkprocessos_varas_nome_idx` (`varas_id` ASC),
  CONSTRAINT `fkprocessos_varas_nome`
    FOREIGN KEY (`varas_id`)
    REFERENCES `juridico`.`varas` (`varas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`partes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`partes` ;

CREATE TABLE IF NOT EXISTS `juridico`.`partes` (
  `partes_id` INT NOT NULL AUTO_INCREMENT,
  `pessoas_id` INT NOT NULL,
  `processos_id` INT NOT NULL,
  `partes_tipo` CHAR(50) NOT NULL,
  `partes_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`partes_id`),
  INDEX `fkpessoas_id_idx` (`pessoas_id` ASC),
  CONSTRAINT `fkpartes_pessoas_id`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `juridico`.`pessoas` (`pessoas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkpartes_processos_id`
    FOREIGN KEY (`processos_id`)
    REFERENCES `juridico`.`processos` (`processos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`indices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`indices` ;

CREATE TABLE IF NOT EXISTS `juridico`.`indices` (
  `indices_id` INT NOT NULL AUTO_INCREMENT,
  `indices_desc` VARCHAR(100) NOT NULL,
  `indices_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`indices_id`),
  UNIQUE INDEX `indice_desc_UNIQUE` (`indices_desc` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`indicesprocesso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`indicesprocesso` ;

CREATE TABLE IF NOT EXISTS `juridico`.`indicesprocesso` (
  `indicesProcesso_id` INT NOT NULL AUTO_INCREMENT,
  `indices_id` INT NOT NULL,
  `processos_id` INT NOT NULL,
  `indice_del` CHAR(1) NULL,
  PRIMARY KEY (`indicesProcesso_id`),
  INDEX `fkindicesProcesso_indices_id_idx` (`indices_id` ASC),
  INDEX `fkindicesProcesso_processos_id_idx` (`processos_id` ASC),
  CONSTRAINT `fkindicesProcesso_indices_id`
    FOREIGN KEY (`indices_id`)
    REFERENCES `juridico`.`indices` (`indices_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkindicesProcesso_processos_id`
    FOREIGN KEY (`processos_id`)
    REFERENCES `juridico`.`processos` (`processos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`tipos_andamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`tipos_andamento` ;

CREATE TABLE IF NOT EXISTS `juridico`.`tipos_andamento` (
  `tipos_andamento_id` INT NOT NULL AUTO_INCREMENT,
  `tipos_andamento_desc` VARCHAR(45) NOT NULL,
  `tipos_andamento_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`tipos_andamento_id`),
  UNIQUE INDEX `tipo_andamento_desc_UNIQUE` (`tipos_andamento_desc` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`andamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`andamentos` ;

CREATE TABLE IF NOT EXISTS `juridico`.`andamentos` (
  `andamentos_id` INT NOT NULL AUTO_INCREMENT,
  `processos_id` INT NOT NULL,
  `tipos_andamento_id` INT NOT NULL,
  `andamentos_com` LONGTEXT NOT NULL,
  `andamentos_data` DATE NOT NULL,
  `andamentos_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`andamentos_id`),
  INDEX `fkandamentos_processos_id_idx` (`processos_id` ASC),
  INDEX `fkandamentos_tipo_andamentos_desc_idx` (`tipos_andamento_id` ASC),
  CONSTRAINT `fkandamentos_processos_id`
    FOREIGN KEY (`processos_id`)
    REFERENCES `juridico`.`processos` (`processos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkandamentos_tipo_andamentos_desc`
    FOREIGN KEY (`tipos_andamento_id`)
    REFERENCES `juridico`.`tipos_andamento` (`tipos_andamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`arquivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`arquivos` ;

CREATE TABLE IF NOT EXISTS `juridico`.`arquivos` (
  `arquivos_id` INT NOT NULL AUTO_INCREMENT,
  `andamentos_id` INT NOT NULL,
  `arquivos_nome` VARCHAR(45) NULL,
  `arquivos_tipo` VARCHAR(255) NULL,
  `arquivos_tamanho` DOUBLE NULL,
  `arquivos_arq` LONGBLOB NULL,
  `arquivos_del` CHAR(1) NOT NULL,
  PRIMARY KEY (`arquivos_id`),
  INDEX `fkandamentos_id_idx` (`andamentos_id` ASC),
  CONSTRAINT `fkarquivos_andamentos_id`
    FOREIGN KEY (`andamentos_id`)
    REFERENCES `juridico`.`andamentos` (`andamentos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `juridico`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `juridico`.`logs` ;

CREATE TABLE IF NOT EXISTS `juridico`.`logs` (
  `logs_id` INT NOT NULL AUTO_INCREMENT,
  `logs_data` TIMESTAMP(0) NULL,
  `logs_usuario` VARCHAR(45) NULL,
  `logs_tipo` VARCHAR(255) NULL,
  `logs_del` CHAR(1) NULL,
  PRIMARY KEY (`logs_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `juridico`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `juridico`;
INSERT INTO `juridico`.`usuarios` (`usuarios_id`, `usuarios_nome`, `usuarios_senha`, `usuarios_grupo`, `usuarios_del`) VALUES (default, 'andrei', 'e10adc3949ba59abbe56e057f20f883e', 1, 'n');

COMMIT;


-- -----------------------------------------------------
-- Data for table `juridico`.`pessoas`
-- -----------------------------------------------------
START TRANSACTION;
USE `juridico`;
INSERT INTO `juridico`.`pessoas` (`pessoas_id`, `usuarios_id`, `pessoas_cpf_cnpj`, `pessoas_rg`, `pessoas_nome`, `pessoas_datanasc`, `pessoas_email`, `pessoas_tel`, `pessoas_sexo`, `pessoas_oab`, `pessoas_endereco`, `pessoas_del`) VALUES (default, null, '46041283835', '456269502', 'Andrei', '1998-01-13', 'emersoncorrea@funprev.bauru.br', '14997016950', 'M', '12345', NULL, 'N');

COMMIT;

